arch:
  - amd64
  - aarch64
backup: hot
boot: auto
description: 'Traefik for home assistant'
env_vars:
  - key: HAOS_CONVERTER_BASHIO_VERSION
    value: 0.17.5
    editable: false
  - key: HAOS_CONVERTER_PM
    value: apk
    editable: false
  - key: TRAEFIK_CONFIGFILE
    value: /data/traefik.yml
    editable: false
  - key: TRAEFIK_PROVIDERS_FILE_DIRECTORY
    value: /data/dynamic
    editable: false
  - key: TRAEFIK_PROVIDERS_FILE_WATCH
    value: 'true'
    editable: false
  - key: TRAEFIK_PROVIDERS_DOCKER
    value: 'false'
    editable: false
  - key: TRAEFIK_API_DASHBOARD
    value: 'true'
    editable: false
environment:
  HAOS_CONVERTER_BASHIO_VERSION: 0.17.5
  HAOS_CONVERTER_PM: apk
  TRAEFIK_CONFIGFILE: /data/traefik.yml
  TRAEFIK_PROVIDERS_FILE_DIRECTORY: /data/dynamic
  TRAEFIK_PROVIDERS_FILE_WATCH: 'true'
  TRAEFIK_PROVIDERS_DOCKER: 'false'
  TRAEFIK_API_DASHBOARD: 'true'
ingress: true
ingress_entry: /dashboard/
ingress_port: 8080
ingress_stream: false
name: 'traefik 3'
options:
  env_vars: []
panel_admin: true
panel_icon: 'mdi:link-variant'
panel_title: traefik
ports:
  80/tcp: null
  443/tcp: null
  8080/tcp: null
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  8080/tcp: Dashboard
schema:
  env_vars:
    - str
slug: traefik_3
startup: application
url: 'https://doc.traefik.io/traefik/'
version: 3.6.9
