arch:
  - amd64
  - aarch64
backup: hot
boot: auto
description: 'Web-Converter zum Konvertieren von Docker-Images in Home Assistant Apps.'
env_vars:
  - key: HAOS_CONVERTER_BASHIO_VERSION
    value: 0.17.5
    editable: false
  - key: CONVERTER_DATA_DIR
    value: /addons
    editable: false
environment:
  HAOS_CONVERTER_BASHIO_VERSION: 0.17.5
  CONVERTER_DATA_DIR: /addons
ingress: true
ingress_entry: /
ingress_port: 80
ingress_stream: false
map:
  - type: addons
    read_only: false
name: 'HAOS App Converter'
panel_admin: true
panel_icon: 'mdi:toy-brick'
panel_title: 'App Converter'
slug: haos_app_converter
startup: application
timeout: 20
url: 'https://github.com/axute/haos-app-converter'
version: 1.10.0
watchdog: 'http://[HOST]:[PORT:80]/'
